<?php


const OWNER_ROLE = 1;
const EMPLOYEE_ROLE = 2;

const PAGINATE_SMALL = 10;
const PAGINATE_MEDIUM = 25;
const PAGINATE_LARGE = 50;
const PAGINATE_EXTRA_LARGE = 100;
const PAGINATION_LIMIT = 200;
